services:
    proof-arrive-api:
      image: ghcr.io/mua-wallace/proof-arrive-api:latest
      container_name: proof-arrive-api
    build:
      context: .
      dockerfile: Dockerfile
      target: production