services:
  proof-arrive-api:
    image: ghcr.io/mua-wallace/proof-arrive-api:latest
    container_name: global-network
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PREFIX: ${API_PREFIX}
      PORT: ${PORT}
      APP_MODE: ${APP_MODE}
      APP_NAME: ${APP_NAME}
      APP_DOCS: ${APP_DOCS}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION_DAYS: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
      MALAMBI_API_BASE_URL: ${MALAMBI_API_BASE_URL}
      MALAMBI_API_BASE_URL_GEOZONE: ${MALAMBI_API_BASE_URL_GEOZONE}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - global-network
networks:
  global-network:
    external: true
